### ISSUE TITLE
Introduction of $wgOAuthMigrateUsersByUsername breaks existing accounts

### ISSUE THREAD

**Issue by tgr** [WikibaseSolutions/WSOAuth#3]
With the introduction of `wgOAuthMigrateUsersByUsername`, all existing accounts become unavailable on wikis using the default settings, as soon as they upgrade to a version that includes feeaac63, since accounts created before the upgrade have not been registered in the `wsoauth_users` table.

**Comment by 26** [comment]
I was aware this issue existed, and I should have made it more clear on the extension's page. The commit [a4462d0](https://github.com/WikibaseSolutions/WSOAuth/commit/a4462d08e1781cac0ed001ccd4863233a0e1506e) adds a maintenance script that allows site administrators to manually migrate specific or all users. This maintenance script does not look at the `wgOAuthMigrateUsersByUsername` setting.

Unfortunately, this maintenance script is not very useful on large wiki's with many external and local accounts. A site administrator cannot be expected to keep track of which accounts were created by WSOAuth and which accounts are local. Migrating all accounts to WSOAuth on a wiki with local accounts is also not a good idea, since it would enable unauthorised account usurpation.

WSOAuth cannot be made to automatically migrate accounts, since it did not keep track of which accounts it created before version 3.0. It may be possible to tell external and external accounts apart by looking at whether they have a password in the database or not (external accounts do not), but I have not researched this possibility yet and I do not think it guarantees an account was created by WSOAuth.

**Comment by tgr** [comment]
Yeah, the reason a user does not have a password could be any other remote authentication provider, or because it is a system user (letting those to be usurped would probably be bad), or even because the account has been disabled in a certain way. And users might have been created with a password and then usurped by (pre-a4462d0) WSOAuth, in which case they would still have a password but the expectation would be that they can log in. You can check the account creation logs (which will use a different subtype for local account creation vs. autocreation of a local account for an upstream identity) but that will also suffer from the same problems.
