### ISSUE TITLE
Port number ignored in $wgOAuthRedirectUri

### ISSUE THREAD

**Issue by tgr** [WikibaseSolutions/WSOAuth#4]
Steps to reproduce: set up the vagrant role in [this patch](https://gerrit.wikimedia.org/r/c/mediawiki/vagrant/+/584900), which will produce the following settings:
```
$wgOAuthAuthProvider = "mediawiki";
$wgOAuthClientId = "3ddb6e3bff0202d10356e88ee6451713";
$wgOAuthClientSecret = "8addbe4a45014fdb3f810b160117c2a342e0cd18";
$wgOAuthRedirectUri = "http://dev.wiki.local.wmftest.net:8765/wiki/Special:PluggableAuthLogin"; // port number might be different, depends on the Vagrant instance
$wgOAuthUri = "https://meta.wikimedia.beta.wmflabs.org/w/index.php?title=Special:OAuth";
```
Try to log in; after the authorization dialog, the user is redirected to `http://dev.wiki.local.wmftest.net/?oauth_verifier=<snip>&oauth_token=<snip>` (notice the lack of port number).

**Comment by 26** [comment]
The configuration variable `$wgOAuthRedirectUri` is not valid for the provider `mediawiki`, since the redirect URL must be configured on the OAuth provider's side (in this case, when registering a new OAuth consumer via `Special:OAuthConsumerRegistration/propose`). I will make this more clear on the extension's page.

I tried creating a consumer on my testing environment that redirected to a URI with a port by specifying the port during the consumer registration and this seemed to work as expected.

I believe your issue could be resolved by creating a new OAuth consumer with the following value for the `OAuth "callback" URL` field:

```
http://dev.wiki.local.wmftest.net:8765/wiki/Special:PluggableAuthLogin
```

The current consumer ([here](https://meta.wikimedia.beta.wmflabs.org/w/index.php?title=Special:OAuthListConsumers/view/3ddb6e3bff0202d10356e88ee6451713&name=&publisher=&stage=-1)) does not have the port specified.

**Comment by tgr** [comment]
The current consumer allows the client to specify the port. Vagrant ports are unpredictable because people need to run multiple vagrant boxes, on different ports. Is there any reason not to use `$wgOAuthRedirectUri` if it has been specified? Adding a callback URL seems like a fairly trivial change.

**Comment by 26** [comment]
You were right, it is indeed possible to allow dynamic callback URLs for applications that have enabled this.

Commit 00d066bb464c18ab7d8ab87494787f7361feb1eb adds this feature to the extension. It is now possible to specify a redirect URI via the `$wgOAuthRedirectUri` to which the application will redirect once the user has been authenticated.

However, during my testing, specifying the redirect URI `http://localhost:8080/index.php?title=Special:PluggableAuth` on an application with the callback prefix `http://localhost` resulted in a failed authentication attempt and the error message:

```
oauth_callback must be set, and must be set to &quot;oob&quot; (case-sensitive), or the configured callback must be a prefix of the supplied callback.
```

The login request did work on an application with the callback prefix `http://localhost:8080`. I am not sure why this is happening.

**Comment by tgr** [comment]
Uh, right, we broke that in 3da90f91f. I should probably restore that.

Thanks for the fix!

**Comment by tgr** [comment]
> Uh, right, we broke that in 3da90f91f. I should probably restore that.

This is now [fixed](https://gerrit.wikimedia.org/r/c/mediawiki/extensions/OAuth/+/620502) in master, FWIW.
