### ISSUE TITLE
$wgOAuthCustomAuthProviders fails when following docs

### ISSUE THREAD

**Issue by TrueBrain** [WikibaseSolutions/WSOAuth#6]
The [docs](https://www.mediawiki.org/wiki/Extension:WSOAuth/For_developers) suggest `$wgOAuthCustomAuthProviders` has to be used as follow:

```php
$wgOAuthCustomAuthProviders = [
    'google' => 'GoogleAuth' // OAuth provider "google" uses class "GoogleAuth".
];
```

This failed for me. I had to use:

```php
use AuthenticationProvider\GithubAuth;
$wgOAuthCustomAuthProviders = [
    'github' => GithubAuth::class
];
```

And from what I understand from the code, it really needs the ` ::class`, not a string. But my knowledge of PHP is .. well .. rather limited, so I might be completely wrong :D

**Comment by 26** [comment]
The `::class` keyword is meant for class name resolution, and returns the name of the class preceding it as a string. It is particularly useful for namespaced classes, since those can look confusing when written as a string directly. Although the example was technically not wrong, you are right in that it is much better to use the `class` keyword. I'll update the documentation. Thanks!

**Comment by TrueBrain** [comment]
So I guess my main mistake was to forget the `use AuthenticationProvider\GithubAuth;`. Gotcha :D Tnx!
